steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/langops-stack/apps/langops-rag-app:latest'
      - '-f'
      - 'rag-app/Dockerfile'
      - './rag-app'

images:
  - 'us-central1-docker.pkg.dev/langops-stack/apps/langops-rag-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'